In [1]:
import numpy as np

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [182]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [185]:
np.ones(10) + 4

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [25]:
arr = np.arange(10,51)

In [26]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [27]:
arr = np.arange(10,51,2)

In [28]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [37]:
arr_2d = np.arange(8)

In [38]:
arr_2d

array([0, 1, 2, 3, 4, 5, 6, 7])

In [46]:
import numpy as np

In [47]:
my_matrix = [1,2,3]

In [48]:
my_matrix

[1, 2, 3]

In [49]:
arr = np.array(my_matrix)

In [50]:
arr

array([1, 2, 3])

In [54]:
my_matrix = [[0,1,2],[3,4,5],[6,7,8]]

In [55]:
my_matrix

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [56]:
np.array(my_matrix)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [57]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [66]:
ranarr = np.random.rand(1)

In [67]:
ranarr

array([0.27885536])

In [68]:
ranarr = np.random.rand(25)

In [69]:
ranarr

array([0.54710037, 0.84290954, 0.61006841, 0.13756488, 0.1429187 ,
       0.78064461, 0.14298716, 0.05532248, 0.44167671, 0.99231325,
       0.62145224, 0.35034582, 0.40025703, 0.24558069, 0.40195059,
       0.48144242, 0.23880678, 0.37596966, 0.14516552, 0.7705742 ,
       0.58207661, 0.32307834, 0.8270709 , 0.07492835, 0.51780851])

In [186]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

array([[[-8.10728120e-01, -1.79451147e-01,  1.34290747e+00,
          4.87154023e-01, -1.17951781e+00,  2.33778372e+00,
         -1.69453832e-02, -6.18113239e-01, -1.38583893e+00,
         -4.20418970e-01, -2.35066164e+00, -6.14289646e-01,
          4.03382081e-01, -3.75625912e-01,  9.41760435e-01,
         -8.42549126e-01, -1.62361356e+00,  5.37603247e-01,
          3.70207956e-01,  6.48037559e-01],
        [ 1.65650427e+00, -1.62242512e-01, -3.93399849e-01,
          2.90116396e-01, -1.89311778e-01, -1.00307043e+00,
         -8.02649355e-01,  4.31338229e-02,  1.93362552e-01,
          8.34322639e-01,  1.50640055e+00,  3.51168413e-01,
          1.30973021e-01, -2.42712946e+00,  5.84537183e-01,
         -2.16939980e+00, -8.28173850e-02, -5.24139848e-01,
         -9.83063303e-01, -3.11983915e-01],
        [ 8.29215754e-01, -1.13612163e+00,  2.86983574e-01,
          5.17988974e-01, -1.02937726e+00, -1.12662297e-01,
         -1.43373431e+00,  5.64619368e-01,  1.20258672e+00,
          6.

In [79]:
mat = np.arange(1,26).reshape(5,5)

In [80]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [139]:
mat[2:5,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [144]:
np.max(mat)

25

In [146]:
mat_2d = np.arange(1,26).reshape(5,5)

In [147]:
mat_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [153]:
mat_2d[3][4]

20

In [188]:
mat_2d[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [189]:
mat_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [190]:
mat.sum()

325

In [191]:
mat_2d.sum()

325

In [192]:
mat.std()

7.211102550927978

In [193]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])