# Improting CSV data into Python


In [4]:
import pandas as pd

In [5]:
nifty = pd.read_csv("C:/Users/Acer/Desktop/niftydata.csv")
nifty.head()

Date        Close
0  9/17/2007  4494.649902
1  9/18/2007  4546.200195
2  9/19/2007  4732.350098
3  9/20/2007  4747.549805
4  9/21/2007  4837.549805

In [10]:
nifty = pd.read_csv("C:/Users/Acer/Desktop/niftydata.csv", sep=',')
nifty.head()

Date        Close
0  9/17/2007  4494.649902
1  9/18/2007  4546.200195
2  9/19/2007  4732.350098
3  9/20/2007  4747.549805
4  9/21/2007  4837.549805

In [13]:
#Limit the number of rows to import
nifty = pd.read_csv("C:/Users/Acer/Desktop/niftydata.csv", nrows=20)
nifty

Date        Close
0    9/17/2007  4494.649902
1    9/18/2007  4546.200195
2    9/19/2007  4732.350098
3    9/20/2007  4747.549805
4    9/21/2007  4837.549805
5    9/24/2007  4932.200195
6    9/25/2007  4938.850098
7    9/26/2007  4940.500000
8    9/27/2007  5000.549805
9    9/28/2007  5021.350098
10  10-01-2007  5068.950195
11  10-03-2007  5210.799805
12  10-04-2007  5208.649902
13  10-05-2007  5185.850098
14  10-08-2007  5085.100098
15  10-09-2007  5327.250000
16  10-10-2007  5441.450195
17  10-11-2007  5524.850098
18  10-12-2007  5428.250000
19  10/15/2007  5670.399902

In [15]:
#remove the header
nifty = pd.read_csv("C:/Users/Acer/Desktop/niftydata.csv", header = None)
nifty

0             1
0      9/17/2007   4494.649902
1      9/18/2007   4546.200195
2      9/19/2007   4732.350098
3      9/20/2007   4747.549805
4      9/21/2007   4837.549805
...          ...           ...
2514  11/23/2017  10348.750000
2515  11/24/2017  10389.700200
2516  11/27/2017  10399.549810
2517  11/28/2017  10370.250000
2518  11/29/2017  10361.300000

[2519 rows x 2 columns]

In [19]:
#Chnage the name of the header column
nifty = pd.read_csv("C:/Users/Acer/Desktop/niftydata.csv", header = None, names = ['Trade Name','Closing Price'])
nifty.head()

Trade Name  Closing Price
0  9/17/2007    4494.649902
1  9/18/2007    4546.200195
2  9/19/2007    4732.350098
3  9/20/2007    4747.549805
4  9/21/2007    4837.549805

In [24]:
#Specifying the column name as a seprate object
col_name = ['Trade Name','Closing Price']
nifty = pd.read_csv("C:/Users/Acer/Desktop/niftydata.csv", header = None, names = col_name)
nifty.head()

Trade Name  Closing Price
0  9/17/2007    4494.649902
1  9/18/2007    4546.200195
2  9/19/2007    4732.350098
3  9/20/2007    4747.549805
4  9/21/2007    4837.549805

In [25]:
#make the location as a variable
loc = "C:/Users/Acer/Desktop/niftydata.csv"
nifty = pd.read_csv(loc)
nifty.head()

9/17/2007  4494.649902
0  9/18/2007  4546.200195
1  9/19/2007  4732.350098
2  9/20/2007  4747.549805
3  9/21/2007  4837.549805
4  9/24/2007  4932.200195

# Tutorial 2 - Describing a Dataset

In [26]:
import pandas as pd

In [33]:
orders = pd.read_excel("C:/Users/Acer/Desktop/Sample - Superstore Sales.xls",0)
orders.head(2)

Row ID  Order ID Order Date Order Priority  Order Quantity   Sales  \
0       1         3 2010-10-13            Low               6  261.54   
1       2         6 2012-02-20  Not Specified               2    6.93   

   Discount    Ship Mode  Profit  Unit Price  ...       Customer Name  \
0      0.04  Regular Air -213.25       38.94  ...  Muhammed MacIntyre   
1      0.01  Regular Air   -4.64        2.08  ...         Ruben Dartt   

  Province   Region Customer Segment Product Category  \
0  Nunavut  Nunavut   Small Business  Office Supplies   
1  Alberta     West        Corporate  Office Supplies   

            Product Sub-Category  \
0         Storage & Organization   
1  Scissors, Rulers and Trimmers   

                                        Product Name Product Container  \
0   Eldon Base for stackable storage shelf, platinum         Large Box   
1  Kleencut® Forged Office Shears by Acme United ...        Small Pack   

  Product Base Margin  Ship Date  
0                0.80 2010-10-20  
1                0.55 2012-02-21  

[2 rows x 21 columns]

In [35]:
orders.describe()

Row ID      Order ID  Order Quantity         Sales     Discount  \
count  8390.000000   8390.000000     8390.000000   8390.000000  8390.000000   
mean   4195.500000  29932.999166       25.564601   1775.466315     0.049677   
std    2422.128713  17242.133927       14.481768   3585.180194     0.031817   
min       1.000000      3.000000        1.000000      2.240000     0.000000   
25%    2098.250000  14989.500000       13.000000    142.962500     0.020000   
50%    4195.500000  29811.500000       26.000000    449.295000     0.050000   
75%    6292.750000  44539.250000       38.000000   1709.985000     0.080000   
max    8390.000000  59939.000000       50.000000  89061.050000     0.250000   

             Profit   Unit Price  Shipping Cost  Product Base Margin  
count   8390.000000  8390.000000    8390.000000          8327.000000  
mean     181.060342    89.354539      12.841080             0.512504  
std     1197.067399   290.479112      17.271407             0.135600  
min   -14140.701600     0.990000       0.490000             0.350000  
25%      -83.295000     6.480000       3.300000             0.380000  
50%       -1.515000    20.990000       6.070000             0.520000  
75%      162.544500    85.990000      13.990000             0.590000  
max    27220.690000  6783.020000     164.730000             0.850000

In [36]:
orders.describe(include = 'all')

Row ID      Order ID           Order Date Order Priority  \
count   8390.000000   8390.000000                 8390           8390   
unique          NaN           NaN                 1418              5   
top             NaN           NaN  2012-03-28 00:00:00           High   
freq            NaN           NaN                   20           1766   
first           NaN           NaN  2009-01-01 00:00:00            NaN   
last            NaN           NaN  2012-12-30 00:00:00            NaN   
mean    4195.500000  29932.999166                  NaN            NaN   
std     2422.128713  17242.133927                  NaN            NaN   
min        1.000000      3.000000                  NaN            NaN   
25%     2098.250000  14989.500000                  NaN            NaN   
50%     4195.500000  29811.500000                  NaN            NaN   
75%     6292.750000  44539.250000                  NaN            NaN   
max     8390.000000  59939.000000                  NaN            NaN   

        Order Quantity         Sales     Discount    Ship Mode        Profit  \
count      8390.000000   8390.000000  8390.000000         8390   8390.000000   
unique             NaN           NaN          NaN            3           NaN   
top                NaN           NaN          NaN  Regular Air           NaN   
freq               NaN           NaN          NaN         6265           NaN   
first              NaN           NaN          NaN          NaN           NaN   
last               NaN           NaN          NaN          NaN           NaN   
mean         25.564601   1775.466315     0.049677          NaN    181.060342   
std          14.481768   3585.180194     0.031817          NaN   1197.067399   
min           1.000000      2.240000     0.000000          NaN -14140.701600   
25%          13.000000    142.962500     0.020000          NaN    -83.295000   
50%          26.000000    449.295000     0.050000          NaN     -1.515000   
75%          38.000000   1709.985000     0.080000          NaN    162.544500   
max          50.000000  89061.050000     0.250000          NaN  27220.690000   

         Unit Price  ...  Customer Name Province Region Customer Segment  \
count   8390.000000  ...           8390     8390   8390             8390   
unique          NaN  ...            795       13      8                4   
top             NaN  ...    Darren Budd  Ontario   West        Corporate   
freq            NaN  ...             41     1826   1987             3075   
first           NaN  ...            NaN      NaN    NaN              NaN   
last            NaN  ...            NaN      NaN    NaN              NaN   
mean      89.354539  ...            NaN      NaN    NaN              NaN   
std      290.479112  ...            NaN      NaN    NaN              NaN   
min        0.990000  ...            NaN      NaN    NaN              NaN   
25%        6.480000  ...            NaN      NaN    NaN              NaN   
50%       20.990000  ...            NaN      NaN    NaN              NaN   
75%       85.990000  ...            NaN      NaN    NaN              NaN   
max     6783.020000  ...            NaN      NaN    NaN              NaN   

       Product Category Product Sub-Category  \
count              8390                 8390   
unique                3                   17   
top     Office Supplies                Paper   
freq               4605                 1223   
first               NaN                  NaN   
last                NaN                  NaN   
mean                NaN                  NaN   
std                 NaN                  NaN   
min                 NaN                  NaN   
25%                 NaN                  NaN   
50%                 NaN                  NaN   
75%                 NaN                  NaN   
max                 NaN                  NaN   

                                     Product Name Product Container  \
count                                        8390           

In [37]:
orders.describe(include = ['object']) # Which contains only a Chararcter data.

Order Priority    Ship Mode Customer Name Province Region  \
count            8390         8390          8390     8390   8390   
unique              5            3           795       13      8   
top              High  Regular Air   Darren Budd  Ontario   West   
freq             1766         6265            41     1826   1987   

       Customer Segment Product Category Product Sub-Category  \
count              8390             8390                 8390   
unique                4                3                   17   
top           Corporate  Office Supplies                Paper   
freq               3075             4605                 1223   

                                     Product Name Product Container  
count                                        8390              8390  
unique                                       1263                 7  
top     Global High-Back Leather Tilter, Burgundy         Small Box  
freq                                           24              4342

In [38]:
orders.describe(include = ['object','float'])

Order Priority         Sales     Discount    Ship Mode        Profit  \
count            8390   8390.000000  8390.000000         8390   8390.000000   
unique              5           NaN          NaN            3           NaN   
top              High           NaN          NaN  Regular Air           NaN   
freq             1766           NaN          NaN         6265           NaN   
mean              NaN   1775.466315     0.049677          NaN    181.060342   
std               NaN   3585.180194     0.031817          NaN   1197.067399   
min               NaN      2.240000     0.000000          NaN -14140.701600   
25%               NaN    142.962500     0.020000          NaN    -83.295000   
50%               NaN    449.295000     0.050000          NaN     -1.515000   
75%               NaN   1709.985000     0.080000          NaN    162.544500   
max               NaN  89061.050000     0.250000          NaN  27220.690000   

         Unit Price  Shipping Cost Customer Name Province Region  \
count   8390.000000    8390.000000          8390     8390   8390   
unique          NaN            NaN           795       13      8   
top             NaN            NaN   Darren Budd  Ontario   West   
freq            NaN            NaN            41     1826   1987   
mean      89.354539      12.841080           NaN      NaN    NaN   
std      290.479112      17.271407           NaN      NaN    NaN   
min        0.990000       0.490000           NaN      NaN    NaN   
25%        6.480000       3.300000           NaN      NaN    NaN   
50%       20.990000       6.070000           NaN      NaN    NaN   
75%       85.990000      13.990000           NaN      NaN    NaN   
max     6783.020000     164.730000           NaN      NaN    NaN   

       Customer Segment Product Category Product Sub-Category  \
count              8390             8390                 8390   
unique                4                3                   17   
top           Corporate  Office Supplies                Paper   
freq               3075             4605                 1223   
mean                NaN              NaN                  NaN   
std                 NaN              NaN                  NaN   
min                 NaN              NaN                  NaN   
25%                 NaN              NaN                  NaN   
50%                 NaN              NaN                  NaN   
75%                 NaN              NaN                  NaN   
max                 NaN              NaN                  NaN   

                                     Product Name Product Container  \
count                                        8390              8390   
unique                                       1263                 7   
top     Global High-Back Leather Tilter, Burgundy         Small Box   
freq                                           24              4342   
mean                                          NaN               NaN   
std                                           NaN               NaN   
min                                           NaN               NaN   
25%                                           NaN               NaN   
50%                                           NaN               NaN   
75%                                           NaN               NaN   
max                                           NaN               NaN   

        Product Base Margin  
count           8327.000000  
unique                  NaN  
top                     NaN  
freq                    NaN  
mean               0.512504  
std                0.135600  
min                0.350000  
25%                0.380000  
50%                0.520000  
75%                0.590000  
max                0.850000

In [39]:
#describing a specific types of values
orders[orders['Order Priority'] == 'High'].describe()

Row ID      Order ID  Order Quantity         Sales     Discount  \
count  1766.000000   1766.000000     1766.000000   1766.000000  1766.000000   
mean   4275.609287  30507.731597       25.830691   1849.741575     0.049496   
std    2451.172068  17454.367249       14.546134   3552.187759     0.031743   
min       3.000000     32.000000        1.000000      3.410000     0.000000   
25%    2189.500000  15778.750000       13.000000    157.855000     0.020000   
50%    4282.500000  30499.000000       26.000000    464.670000     0.050000   
75%    6467.000000  46042.750000       39.000000   1773.739750     0.080000   
max    8389.000000  59937.000000       50.000000  28664.520000     0.100000   

             Profit   Unit Price  Shipping Cost  Product Base Margin  
count   1766.000000  1766.000000    1766.000000          1753.000000  
mean     230.436621    88.822984      12.827169             0.513383  
std     1294.698329   239.568337      16.905500             0.133201  
min   -11861.460000     1.260000       0.490000             0.350000  
25%      -83.162500     6.680000       3.010000             0.380000  
50%        0.990000    21.980000       6.130000             0.530000  
75%      174.408125    95.820000      13.990000             0.590000  
max    13340.260000  3502.140000     110.200000             0.850000

In [41]:
#makeing a little bit more complex
orders[(orders['Order Priority'] == 'High') & (orders.Sales >= 10000)].describe()

Row ID      Order ID  Order Quantity         Sales   Discount  \
count    68.000000     68.000000       68.000000     68.000000  68.000000   
mean   4548.926471  32442.308824       36.044118  16129.923059   0.043824   
std    2613.045814  18626.326331       10.912725   5094.178907   0.029626   
min      49.000000    293.000000        3.000000  10071.090000   0.000000   
25%    2517.500000  18157.500000       30.000000  12264.360000   0.017500   
50%    4205.000000  29876.500000       39.000000  14709.315000   0.040000   
75%    7193.250000  51314.750000       44.000000  19524.586500   0.070000   
max    8325.000000  59491.000000       50.000000  28664.520000   0.100000   

             Profit   Unit Price  Shipping Cost  Product Base Margin  
count     68.000000    68.000000      68.000000            67.000000  
mean    4003.466282   557.899118      35.634118             0.523881  
std     3948.943598   471.986656      20.791751             0.129169  
min    -8389.470900   208.160000       8.730000             0.350000  
25%     1081.835000   350.605000      19.990000             0.380000  
50%     4306.494000   449.990000      26.000000             0.560000  
75%     7057.997625   550.980000      46.340000             0.600000  
max    13340.260000  3502.140000      99.000000             0.810000

In [43]:
import numpy as np

In [44]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

# Arrange Functions

In [45]:
np.arange(1,15) #start and Stop

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [92]:
np.arange(3.0) #stop

<IPython.core.display.Javascript object>

array([0., 1., 2.])

In [47]:
np.arange(1,10,2) #step

array([1, 3, 5, 7, 9])

In [48]:
np.arange(20,dtype="complex")

array([ 0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,
        7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j, 13.+0.j,
       14.+0.j, 15.+0.j, 16.+0.j, 17.+0.j, 18.+0.j, 19.+0.j])

In [94]:
np.arange(1,100,3, dtype = "float")

<IPython.core.display.Javascript object>

array([ 1.,  4.,  7., 10., 13., 16., 19., 22., 25., 28., 31., 34., 37.,
       40., 43., 46., 49., 52., 55., 58., 61., 64., 67., 70., 73., 76.,
       79., 82., 85., 88., 91., 94., 97.])

In [93]:
np.arange(25, dtype = "float")

<IPython.core.display.Javascript object>

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])

# Array Functions


In [84]:
a=np.array([1,2,3,4])
a

<IPython.core.display.Javascript object>

array([1, 2, 3, 4])

In [85]:
np.array([[2,3],[4,5]])

<IPython.core.display.Javascript object>

array([[2, 3],
       [4, 5]])

In [87]:
np.array([1,2,3],'complex')

<IPython.core.display.Javascript object>

array([1.+0.j, 2.+0.j, 3.+0.j])

In [88]:
np.array((1,2,3)) #Tuples

<IPython.core.display.Javascript object>

array([1, 2, 3])

# Zeros() Functions

In [95]:
help(np.zeros)

<IPython.core.display.Javascript object>

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [96]:
np.zeros(5)

<IPython.core.display.Javascript object>

array([0., 0., 0., 0., 0.])

In [98]:
np.zeros(10,dtype="int")

<IPython.core.display.Javascript object>

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [100]:
np.zeros((5,3))

<IPython.core.display.Javascript object>

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [101]:
np.zeros([5,5])

<IPython.core.display.Javascript object>

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [102]:
np.zeros(4,order='F')

<IPython.core.display.Javascript object>

array([0., 0., 0., 0.])

In [104]:
np.zeros((3,4),order="F")

<IPython.core.display.Javascript object>

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Linspace Function


In [2]:
help(np.linspace)

<IPython.core.display.Javascript object>

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [19]:
np.linspace(1,100, num=5, dtype="complex")

<IPython.core.display.Javascript object>

array([  1.  +0.j,  25.75+0.j,  50.5 +0.j,  75.25+0.j, 100.  +0.j])

In [6]:
np.linspace(2.0, 3.0, num=6, endpoint=False)

<IPython.core.display.Javascript object>

array([2.        , 2.16666667, 2.33333333, 2.5       , 2.66666667,
       2.83333333])

In [11]:
np.linspace(2.0, 3.0, num=5, retstep=True)

<IPython.core.display.Javascript object>

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [20]:
np.linspace(1,100)

<IPython.core.display.Javascript object>

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [21]:
np.linspace(1,100, num =25 )

<IPython.core.display.Javascript object>

array([  1.   ,   5.125,   9.25 ,  13.375,  17.5  ,  21.625,  25.75 ,
        29.875,  34.   ,  38.125,  42.25 ,  46.375,  50.5  ,  54.625,
        58.75 ,  62.875,  67.   ,  71.125,  75.25 ,  79.375,  83.5  ,
        87.625,  91.75 ,  95.875, 100.   ])

# ones() Functions

In [23]:
np.ones(25)

<IPython.core.display.Javascript object>

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.ones(7,dtype="int")

<IPython.core.display.Javascript object>

array([1, 1, 1, 1, 1, 1, 1])

In [25]:
np.ones(10,dtype="complex")

<IPython.core.display.Javascript object>

array([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j,
       1.+0.j, 1.+0.j])

In [26]:
np.ones(7,dtype="float")

<IPython.core.display.Javascript object>

array([1., 1., 1., 1., 1., 1., 1.])

In [29]:
np.ones((6,5))

<IPython.core.display.Javascript object>

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# empty() Functions

In [30]:
np.empty(6)

<IPython.core.display.Javascript object>

array([2.        , 2.16666667, 2.33333333, 2.5       , 2.66666667,
       2.83333333])

In [32]:
np.empty([3,4],dtype=int)

<IPython.core.display.Javascript object>

array([[          0,  1073741824,  1431655765,  1073829205],
       [-1431655765,  1073916586,           0,  1074003968],
       [ 1431655765,  1074091349, -1431655766,  1074178730]])

# Random Functions

In [38]:
#rand()
#randn()
#ranf()
#randint()
np.random.rand(5)  # Uniformally Distributed Values

<IPython.core.display.Javascript object>

array([0.72705371, 0.94979914, 0.51618571, 0.09855798, 0.71948542])

In [39]:
np.random.rand(3,5) # Uniformally Distributed Values

<IPython.core.display.Javascript object>

array([[0.18657755, 0.77460918, 0.58766286, 0.42228832, 0.34160487],
       [0.39113123, 0.31622414, 0.77769977, 0.90196469, 0.84599983],
       [0.0869286 , 0.46601565, 0.09095374, 0.56148574, 0.94623374]])

In [40]:
np.random.randn(3,5) # Normally Distributed Values

<IPython.core.display.Javascript object>

array([[-0.07631359,  1.7519471 , -1.06583191, -0.77396719,  0.74904998],
       [-0.37395885,  0.51770736,  0.32926837, -2.67657536,  0.41826478],
       [ 1.96903424, -0.75808957, -0.60868275,  0.71629481, -0.80607659]])

In [44]:
np.random.randint(9, size=100) 

<IPython.core.display.Javascript object>

array([5, 8, 0, 4, 7, 5, 8, 0, 5, 5, 2, 4, 3, 6, 3, 0, 6, 2, 6, 7, 2, 5,
       6, 3, 4, 1, 7, 4, 3, 2, 2, 2, 7, 6, 8, 5, 4, 0, 1, 8, 3, 2, 0, 2,
       8, 0, 5, 4, 6, 8, 3, 4, 5, 3, 4, 3, 7, 2, 2, 2, 0, 0, 3, 2, 5, 2,
       3, 8, 7, 5, 6, 0, 0, 4, 6, 5, 6, 3, 1, 7, 1, 5, 3, 0, 2, 4, 3, 2,
       7, 4, 4, 7, 2, 1, 3, 4, 7, 1, 6, 7])

In [45]:
np.random.randint(1, size=10) 

<IPython.core.display.Javascript object>

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [46]:
np.random.randint(5, size=(2,4)) 

<IPython.core.display.Javascript object>

array([[4, 2, 1, 2],
       [0, 2, 2, 4]])

# Reading Excel using Pandas - Exploring Options

In [1]:
import pandas as pd

In [3]:
xl_file = pd.ExcelFile("C:/Users/Acer/Desktop/Sample - Superstore Sales.xls")

In [38]:
Orders = xl_file.parse("Orders")
Orders.head()

Row ID  Order ID Order Date Order Priority  Order Quantity      Sales  \
0       1         3 2010-10-13            Low               6   261.5400   
1       2         6 2012-02-20  Not Specified               2     6.9300   
2       3        32 2011-07-15           High              26  2808.0800   
3       4        32 2011-07-15           High              24  1761.4000   
4       5        32 2011-07-15           High              23   160.2335   

   Discount       Ship Mode    Profit  Unit Price  ...       Customer Name  \
0      0.04     Regular Air  -213.250       38.94  ...  Muhammed MacIntyre   
1      0.01     Regular Air    -4.640        2.08  ...         Ruben Dartt   
2      0.07     Regular Air  1054.820      107.53  ...       Liz Pelletier   
3      0.09  Delivery Truck -1748.560       70.89  ...       Liz Pelletier   
4      0.04     Regular Air   -85.129        7.99  ...       Liz Pelletier   

  Province   Region Customer Segment Product Category  \
0  Nunavut  Nunavut   Small Business  Office Supplies   
1  Alberta     West        Corporate  Office Supplies   
2  Alberta     West        Corporate        Furniture   
3  Alberta     West        Corporate        Furniture   
4  Alberta     West        Corporate       Technology   

            Product Sub-Category  \
0         Storage & Organization   
1  Scissors, Rulers and Trimmers   
2             Office Furnishings   
3                         Tables   
4   Telephones and Communication   

                                        Product Name Product Container  \
0   Eldon Base for stackable storage shelf, platinum         Large Box   
1  Kleencut® Forged Office Shears by Acme United ...        Small Pack   
2  Tenex Contemporary Contur Chairmats for Low an...        Medium Box   
3                               KI Conference Tables         Jumbo Box   
4                       Bell Sonecor JB700 Caller ID        Medium Box   

  Product Base Margin  Ship Date  
0                0.80 2010-10-20  
1                0.55 2012-02-21  
2                0.65 2011-07-17  
3                0.72 2011-07-16  
4                0.60 2011-07-17  

[5 rows x 21 columns]

In [8]:
# Read everything in just oneline
returns = pd.read_excel("C:/Users/Acer/Desktop/Sample - Superstore Sales.xls",1) #,1 indicates the second sheet using indexing
returns.head()

Order ID    Status
0        65  Returned
1        69  Returned
2       134  Returned
3       135  Returned
4       230  Returned

# Deleting Row and Columns from the Dataframe

In [28]:
import pandas as pd

In [75]:
orders = pd.read_excel("C:/Users/Acer/Desktop/Sample - Superstore Sales.xls")
orders.head()

Row ID  Order ID Order Date Order Priority  Order Quantity      Sales  \
0       1         3 2010-10-13            Low               6   261.5400   
1       2         6 2012-02-20  Not Specified               2     6.9300   
2       3        32 2011-07-15           High              26  2808.0800   
3       4        32 2011-07-15           High              24  1761.4000   
4       5        32 2011-07-15           High              23   160.2335   

   Discount       Ship Mode    Profit  Unit Price  ...       Customer Name  \
0      0.04     Regular Air  -213.250       38.94  ...  Muhammed MacIntyre   
1      0.01     Regular Air    -4.640        2.08  ...         Ruben Dartt   
2      0.07     Regular Air  1054.820      107.53  ...       Liz Pelletier   
3      0.09  Delivery Truck -1748.560       70.89  ...       Liz Pelletier   
4      0.04     Regular Air   -85.129        7.99  ...       Liz Pelletier   

  Province   Region Customer Segment Product Category  \
0  Nunavut  Nunavut   Small Business  Office Supplies   
1  Alberta     West        Corporate  Office Supplies   
2  Alberta     West        Corporate        Furniture   
3  Alberta     West        Corporate        Furniture   
4  Alberta     West        Corporate       Technology   

            Product Sub-Category  \
0         Storage & Organization   
1  Scissors, Rulers and Trimmers   
2             Office Furnishings   
3                         Tables   
4   Telephones and Communication   

                                        Product Name Product Container  \
0   Eldon Base for stackable storage shelf, platinum         Large Box   
1  Kleencut® Forged Office Shears by Acme United ...        Small Pack   
2  Tenex Contemporary Contur Chairmats for Low an...        Medium Box   
3                               KI Conference Tables         Jumbo Box   
4                       Bell Sonecor JB700 Caller ID        Medium Box   

  Product Base Margin  Ship Date  
0                0.80 2010-10-20  
1                0.55 2012-02-21  
2                0.65 2011-07-17  
3                0.72 2011-07-16  
4                0.60 2011-07-17  

[5 rows x 21 columns]

In [46]:
Orders.drop('Row ID',axis=1,inplace=True)
Orders.head(2)

Order ID Order Date Order Priority  Order Quantity   Sales  Discount  \
0         3 2010-10-13            Low               6  261.54      0.04   
1         6 2012-02-20  Not Specified               2    6.93      0.01   

     Ship Mode  Profit  Unit Price  Shipping Cost       Customer Name  \
0  Regular Air -213.25       38.94          35.00  Muhammed MacIntyre   
1  Regular Air   -4.64        2.08           2.56         Ruben Dartt   

  Province   Region Customer Segment Product Category  \
0  Nunavut  Nunavut   Small Business  Office Supplies   
1  Alberta     West        Corporate  Office Supplies   

            Product Sub-Category  \
0         Storage & Organization   
1  Scissors, Rulers and Trimmers   

                                        Product Name Product Container  \
0   Eldon Base for stackable storage shelf, platinum         Large Box   
1  Kleencut® Forged Office Shears by Acme United ...        Small Pack   

   Product Base Margin  Ship Date  
0                 0.80 2010-10-20  
1                 0.55 2012-02-21

In [76]:
orders = pd.read_excel("C:/Users/Acer/Desktop/Sample - Superstore Sales.xls",0) #,0 indicates the second sheet using indexing
orders.head()

Row ID  Order ID Order Date Order Priority  Order Quantity      Sales  \
0       1         3 2010-10-13            Low               6   261.5400   
1       2         6 2012-02-20  Not Specified               2     6.9300   
2       3        32 2011-07-15           High              26  2808.0800   
3       4        32 2011-07-15           High              24  1761.4000   
4       5        32 2011-07-15           High              23   160.2335   

   Discount       Ship Mode    Profit  Unit Price  ...       Customer Name  \
0      0.04     Regular Air  -213.250       38.94  ...  Muhammed MacIntyre   
1      0.01     Regular Air    -4.640        2.08  ...         Ruben Dartt   
2      0.07     Regular Air  1054.820      107.53  ...       Liz Pelletier   
3      0.09  Delivery Truck -1748.560       70.89  ...       Liz Pelletier   
4      0.04     Regular Air   -85.129        7.99  ...       Liz Pelletier   

  Province   Region Customer Segment Product Category  \
0  Nunavut  Nunavut   Small Business  Office Supplies   
1  Alberta     West        Corporate  Office Supplies   
2  Alberta     West        Corporate        Furniture   
3  Alberta     West        Corporate        Furniture   
4  Alberta     West        Corporate       Technology   

            Product Sub-Category  \
0         Storage & Organization   
1  Scissors, Rulers and Trimmers   
2             Office Furnishings   
3                         Tables   
4   Telephones and Communication   

                                        Product Name Product Container  \
0   Eldon Base for stackable storage shelf, platinum         Large Box   
1  Kleencut® Forged Office Shears by Acme United ...        Small Pack   
2  Tenex Contemporary Contur Chairmats for Low an...        Medium Box   
3                               KI Conference Tables         Jumbo Box   
4                       Bell Sonecor JB700 Caller ID        Medium Box   

  Product Base Margin  Ship Date  
0                0.80 2010-10-20  
1                0.55 2012-02-21  
2                0.65 2011-07-17  
3                0.72 2011-07-16  
4                0.60 2011-07-17  

[5 rows x 21 columns]

In [77]:
orders.drop(['Order Date','Order Priority'],axis = 1, inplace = True)

In [79]:
orders.head(2)

Row ID  Order ID  Order Quantity   Sales  Discount    Ship Mode  Profit  \
0       1         3               6  261.54      0.04  Regular Air -213.25   
1       2         6               2    6.93      0.01  Regular Air   -4.64   

   Unit Price  Shipping Cost       Customer Name Province   Region  \
0       38.94          35.00  Muhammed MacIntyre  Nunavut  Nunavut   
1        2.08           2.56         Ruben Dartt  Alberta     West   

  Customer Segment Product Category           Product Sub-Category  \
0   Small Business  Office Supplies         Storage & Organization   
1        Corporate  Office Supplies  Scissors, Rulers and Trimmers   

                                        Product Name Product Container  \
0   Eldon Base for stackable storage shelf, platinum         Large Box   
1  Kleencut® Forged Office Shears by Acme United ...        Small Pack   

   Product Base Margin  Ship Date  
0                 0.80 2010-10-20  
1                 0.55 2012-02-21

In [80]:
orders.drop([2,3],axis=0,inplace=True)

In [82]:
orders.head()

Row ID  Order ID  Order Quantity     Sales  Discount    Ship Mode   Profit  \
0       1         3               6  261.5400      0.04  Regular Air -213.250   
1       2         6               2    6.9300      0.01  Regular Air   -4.640   
4       5        32              23  160.2335      0.04  Regular Air  -85.129   
5       6        32              15  140.5600      0.04  Regular Air -128.380   
6       7        35              30  288.5600      0.03  Regular Air   60.720   

   Unit Price  Shipping Cost       Customer Name          Province   Region  \
0       38.94          35.00  Muhammed MacIntyre           Nunavut  Nunavut   
1        2.08           2.56         Ruben Dartt           Alberta     West   
4        7.99           5.03       Liz Pelletier           Alberta     West   
5        8.46           8.99       Liz Pelletier       Saskachewan   Prarie   
6        9.11           2.25     Julie Creighton  British Columbia     West   

  Customer Segment Product Category           Product Sub-Category  \
0   Small Business  Office Supplies         Storage & Organization   
1        Corporate  Office Supplies  Scissors, Rulers and Trimmers   
4        Corporate       Technology   Telephones and Communication   
5        Corporate       Technology           Computer Peripherals   
6        Corporate  Office Supplies            Pens & Art Supplies   

                                        Product Name Product Container  \
0   Eldon Base for stackable storage shelf, platinum         Large Box   
1  Kleencut® Forged Office Shears by Acme United ...        Small Pack   
4                       Bell Sonecor JB700 Caller ID        Medium Box   
5                  Imation 3.5 IBM Diskettes, 10/Box        Small Pack   
6        Dixon Ticonderoga Core-Lock Colored Pencils          Wrap Bag   

   Product Base Margin  Ship Date  
0                 0.80 2010-10-20  
1                 0.55 2012-02-21  
4                 0.60 2011-07-17  
5                 0.79 2011-07-16  
6                 0.52 2011-10-23

# IF Statement

In [47]:
if 5 ==15/3:
    print("God Almighty")

God Almighty


In [51]:
if 5!= 3*6:
    print("Oh God")

Oh God


# ELIF Statement

In [55]:
x = 5
if x > 3:
    print("Case 1")
if x <= 3:
    print("Case 2")

Case 1


In [59]:
def Compare_to_five(y):
    if y>5:
        return "Greater"
    elif y<5:
        return "less"
    else:
        return "Equal"    

In [60]:
print(Compare_to_five(5))

Equal


In [61]:
print(Compare_to_five(10))

Greater


In [62]:
print(Compare_to_five(4))

less


In [63]:
def Compare_to_five(y):
    if y>5:
        return "Greater"
    elif y < 0:
        return "Negative"
    elif y<5:
        return "less"
    else:
        return "Equal"  

In [64]:
print(Compare_to_five(-2))

Negative


In [65]:
def plus_ten(a):
    return a+10

In [66]:
plus_ten(5)

15

In [67]:
plus_ten(6)

16

In [71]:
def plus_nine(a):
    result = a+9
    print ('Outcome')
    return result

In [72]:
plus_nine(2)

Outcome


11

# Using A function in another function

In [77]:
def wage(w_hours):
    return w_hours * 25
def with_bonus(w_hours):
    return wage(w_hours) +50

In [78]:
wage(8)

200

In [79]:
with_bonus(8)

250

# Combining Conditional Statements and Functions

In [82]:
def add_10(m):
    if m >= 100:
        m = m+10
        return m
    else:
        return "Save More Johny !"

In [84]:
add_10(100)

110

In [85]:
add_10(99)

'Save More Johny !'

# Creating Functions Containing a Few Arguments

In [87]:
def subtract_bc(a,b,c):
    result = a-b*c
    print('Parameter a equals', a)
    print('Parameter b equals', b)
    print('Parameter c equals', c)
    return result

In [89]:
subtract_bc(10,3,2)

Parameter a equals 10
Parameter b equals 3
Parameter c equals 2


4

In [90]:
subtract_bc(a=10,b=3,c=2)

Parameter a equals 10
Parameter b equals 3
Parameter c equals 2


4

# List Slicing

In [95]:
Participants = ['John','Peter','Maria','leila','Dawan','Catherine']
Participants

['John', 'Peter', 'Maria', 'leila', 'Dawan', 'Catherine']

In [98]:
Participants.index("Maria")

2

In [99]:
Newcomers = ['Jonse','france']
Newcomers

['Jonse', 'france']

In [100]:
Full_list =[Participants,Newcomers]
Full_list

[['John', 'Peter', 'Maria', 'leila', 'Dawan', 'Catherine'],
 ['Jonse', 'france']]

In [101]:
Participants.sort()
Participants

['Catherine', 'Dawan', 'John', 'Maria', 'Peter', 'leila']

In [102]:
Participants.sort(reverse=True)
Participants

['leila', 'Peter', 'Maria', 'John', 'Dawan', 'Catherine']

In [103]:
Numbers = [1,2,3,4,5,6,7,8,9,0]
Numbers

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]

In [105]:
Numbers.sort()
Numbers

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [106]:
Numbers.sort(reverse=True)
Numbers

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

# Dictionaries

In [108]:
dict = {'k1':"Cat",'k2':"dog",'k3':"mouse",'k4':"fish"}
dict

{'k1': 'Cat', 'k2': 'dog', 'k3': 'mouse', 'k4': 'fish'}

In [109]:
dict['k1']

'Cat'

In [110]:
dict['k4']

'fish'

In [111]:
dict['k5']="Parrot"
dict

{'k1': 'Cat', 'k2': 'dog', 'k3': 'mouse', 'k4': 'fish', 'k5': 'Parrot'}

In [113]:
dict['k2']="Squerriel"
dict

{'k1': 'Cat', 'k2': 'Squerriel', 'k3': 'mouse', 'k4': 'fish', 'k5': 'Parrot'}

In [115]:
dep_workers ={'dep_1':'Peter','dep_2':['Jenifer','Mike', 'Jain']}
dep_workers['dep_2']

['Jenifer', 'Mike', 'Jain']

In [116]:
Team = {}
Team['Point Gaurd']='Drink'
Team['Shooting Gaurd']= 'Al'
Team['Small Forward']='Sean'
Team['Power Forward']='Alexander'
Team['Center']='Hector'

In [117]:
print(Team)

{'Point Gaurd': 'Drink', 'Shooting Gaurd': 'Al', 'Small Forward': 'Sean', 'Power Forward': 'Alexander', 'Center': 'Hector'}


In [118]:
print(Team['Center'])

Hector


In [119]:
print (Team.get('Small Forward'))

Sean


In [121]:
print(Team.get('coach'))

None


# For Loops

In [122]:
even = [0,2,4,6,8,10,12,14,16,18,20]

In [128]:
for n in even:
    print(n, end = ' ')

0 2 4 6 8 10 12 14 16 18 20 

# While loop and Incrementing

In [133]:
x = 0
while x<=20:
    print(x, end=' ')
    x=x+2

0 2 4 6 8 10 12 14 16 18 20 

In [132]:
x = 0
while x<=20:
    print(x, end=' ')
    x+=2

0 2 4 6 8 10 12 14 16 18 20 

# Lists with range() Function

In [135]:
range(10)

range(0, 10)

In [136]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [138]:
range(3,7)

range(3, 7)

In [139]:
list(range(3,7))

[3, 4, 5, 6]

In [140]:
range(1,20,2)

range(1, 20, 2)

In [141]:
list(range(1,20,2))

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

# Conditional statments and Loops

In [149]:
for n in range(20):
    print(2**n,end =' ')
    

1 2 4 8 16 32 64 128 256 512 1024 2048 4096 8192 16384 32768 65536 131072 262144 524288 

In [154]:
for x in range(20):
    if x % 2 == 0:
        print (x, end = " ")
    else:
        print("Addada",end=" ")    

0 Addada 2 Addada 4 Addada 6 Addada 8 Addada 10 Addada 12 Addada 14 Addada 16 Addada 18 Addada 

In [155]:
x= [0,1,2]

In [156]:
for item in x:
    print(item, end = " ")

0 1 2 

In [157]:
for item in range(len(x)):
    print(x[item], end = ' ')

0 1 2 

# Conditional statements, Functions and Loops

In [160]:
def count(numbers):
    total = 0
    for x in numbers:
        if x < 20:
            total +=1
    return total

In [161]:
list_1=[1,3,7,9,15, 19 ,21,18, 23]
count(list_1)

7

# How to iterate over Dictionaries


In [162]:
prices = {
    "Box of Spaggati":4,
    "Noodles":5,
    "Cheese":2
}
quantity = {
    "Box of Spaggati":6,
    "Noodles":10,
    "Cheese":0
}

money_spent = 0

for i in quantity:
    money_spent = money_spent + (prices[i]*quantity[i])
    
print(money_spent)
    

74
